layout_spectrum: 1
typography_spectrum: 0.7883642
color:
  lightness: 0.2469658
  brandStrength: 0.7824621
  saturation: 0.2105525
  rhythmicContrast: 0.2079641
  brandColors:
    - '#101010'
    - '#777777'
    - '#AAAAAA'
    - '#FFFFFF'
    - '#F94008'
name: NBM
