layout_spectrum: 0.7074199
typography_spectrum: 0.3895447
color:
  lightness: 0.2469658
  brandStrength: 0.2099494
  saturation: 0.2105525
  rhythmicContrast: 0.2079641
  brandColors:
    - '#D80000'
    - '#000000'
    - '#9E9E9E'
    - '#DCDCDC'
    - '#424242'
name: Nathanael Murphy
